// examples/frontend/angular/src/app/components/layout/header.component.ts
/**
 * @file Application header component.
 *
 * Renders the top navigation bar with:
 * - **Left**: Ximplicity logo (dark or light variant depending on
 *   the active theme) and the application title.
 * - **Right**: Theme toggle, language selector, and user
 *   authentication controls (login / user name + logout).
 */

import { Component, inject, computed } from '@angular/core';
import { RouterLink } from '@angular/router';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { TranslateModule } from '@ngx-translate/core';
import { AsyncPipe } from '@angular/common';
import { ThemeService } from '@app/services/theme.service';
import { ThemeToggleComponent } from '@app/components/common/theme-toggle.component';
import { LanguageSelectorComponent } from '@app/components/common/language-selector.component';

/**
 * Standalone header component.
 *
 * Mirrors the React Header layout: logo and title on the left,
 * theme toggle, language selector, and auth controls on the right.
 *
 * @example
 * ```html
 * <app-header />
 * ```
 */
@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    RouterLink,
    TranslateModule,
    AsyncPipe,
    ThemeToggleComponent,
    LanguageSelectorComponent,
  ],
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  /** OIDC service for authentication state and actions. */
  protected readonly oidcService = inject(OidcSecurityService);

  /** Theme service to determine which logo variant to display. */
  protected readonly themeService = inject(ThemeService);

  /** Observable that emits the authentication state. */
  readonly isAuthenticated$ = this.oidcService.isAuthenticated$;

  /** Observable that emits the user data from the token. */
  readonly userData$ = this.oidcService.userData$;

  /**
   * Computed signal that resolves the logo asset path based on the
   * current theme.
   */
  readonly logoSrc = computed(() =>
    this.themeService.isDark()
      ? '/assets/branding/dark-color-logo-with-claim.svg'
      : '/assets/branding/light-color-logo-with-claim.svg',
  );

  /**
   * Initiates the OIDC login flow by redirecting to Keycloak.
   */
  login(): void {
    this.oidcService.authorize();
  }

  /**
   * Initiates the OIDC logout flow.
   */
  logout(): void {
    this.oidcService.logoff().subscribe();
  }

  /**
   * Extracts a display name from the user data object.
   *
   * @param userData - The decoded token user data from Keycloak.
   * @returns The preferred username, full name, email, or empty string.
   */
  getUserName(userData: Record<string, unknown> | null): string {
    if (!userData) return '';
    return (
      (userData['preferred_username'] as string) ??
      (userData['name'] as string) ??
      (userData['email'] as string) ??
      ''
    );
  }
}

<!-- Application header bar -->
<header class="app-header">
  <!-- Left: Logo + Title -->
  <a routerLink="/" class="app-header-left" style="text-decoration: none">
    <img
      [src]="logoSrc()"
      alt="Ximplicity"
      class="app-header-logo"
    />
    <span class="app-header-title">{{ 'app.title' | translate }}</span>
  </a>

  <!-- Right: Controls -->
  <div class="app-header-right">
    <app-theme-toggle />
    <app-language-selector />

    @if (isAuthenticated$ | async; as authResult) {
      @if (authResult.isAuthenticated) {
        @if (userData$ | async; as userResult) {
          <span class="header-user-name">{{ getUserName(userResult.userData) }}</span>
        }
        <button
          class="btn btn-sm"
          type="button"
          (click)="logout()"
        >
          {{ 'header.logout' | translate }}
        </button>
      } @else {
        <button
          class="btn btn-sm btn-primary"
          type="button"
          (click)="login()"
        >
          {{ 'header.login' | translate }}
        </button>
      }
    } @else {
      <button
        class="btn btn-sm btn-primary"
        type="button"
        (click)="login()"
      >
        {{ 'header.login' | translate }}
      </button>
    }
  </div>
</header>

// examples/frontend/react/src/components/layout/Header.tsx
/**
 * @file Application header component.
 *
 * Renders the top navigation bar with:
 * - **Left**: Ximplicity logo (dark or light variant depending on
 *   the active theme) and the application title.
 * - **Right**: Theme toggle, language selector, and user
 *   authentication controls (login / user name + logout).
 */

import React from "react";
import { useAuth } from "react-oidc-context";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useTheme } from "@/hooks/useTheme";
import { ThemeToggle } from "@/components/common/ThemeToggle";
import { LanguageSelector } from "@/components/common/LanguageSelector";

/* ------------------------------------------------------------------
 * Logo imports.
 * Vite resolves these static asset imports to hashed URLs at build
 * time, which works correctly even when the source files live outside
 * the `src/` directory (Vite follows the import graph).
 * ------------------------------------------------------------------ */
import darkLogo from "../../../../../assets/branding/dark-color-logo-with-claim.svg";
import lightLogo from "../../../../../assets/branding/light-color-logo-with-claim.svg";

/**
 * Application header bar.
 *
 * The header is a flexbox row divided into a left section (branding)
 * and a right section (controls).  It adapts its logo variant to the
 * current theme automatically via the {@link useTheme} hook.
 *
 * @returns The rendered header element.
 *
 * @example
 * ```tsx
 * <Header />
 * ```
 */
export function Header(): React.JSX.Element {
  const { theme } = useTheme();
  const auth = useAuth();
  const { t } = useTranslation();

  const logo = theme === "dark" ? darkLogo : lightLogo;
  const userName = auth.user?.profile?.preferred_username
    ?? auth.user?.profile?.name
    ?? auth.user?.profile?.email
    ?? "";

  return (
    <header className="app-header">
      {/* -------- Left: Logo + Title -------- */}
      <Link to="/" className="app-header-left" style={{ textDecoration: "none" }}>
        <img
          src={logo}
          alt="Ximplicity"
          className="app-header-logo"
        />
        <span className="app-header-title">
          {t("app.title")}
        </span>
      </Link>

      {/* -------- Right: Controls -------- */}
      <div className="app-header-right">
        <ThemeToggle />
        <LanguageSelector />

        {auth.isAuthenticated ? (
          <>
            <span className="header-user-name">{userName}</span>
            <button
              className="btn btn-sm"
              onClick={() => auth.signoutRedirect()}
              type="button"
            >
              {t("header.logout")}
            </button>
          </>
        ) : (
          <button
            className="btn btn-sm btn-primary"
            onClick={() => auth.signinRedirect()}
            type="button"
          >
            {t("header.login")}
          </button>
        )}
      </div>
    </header>
  );
}
