// examples/frontend/angular/src/app/components/layout/layout.component.ts
/**
 * @file Application layout component.
 *
 * Provides the top-level page shell that wraps every route:
 * Header at the top, a `<main>` area with the `<router-outlet>` in
 * the middle, and Footer at the bottom.
 */

import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HeaderComponent } from './header.component';
import { FooterComponent } from './footer.component';

/**
 * Standalone layout component that assembles the app shell.
 *
 * @example
 * ```html
 * <app-layout />
 * ```
 */
@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, HeaderComponent, FooterComponent],
  templateUrl: './layout.component.html',
})
export class LayoutComponent {}

<!-- Application shell: header + routed content + footer -->
<div class="app-layout">
  <app-header />
  <main class="app-main">
    <router-outlet />
  </main>
  <app-footer />
</div>

// examples/frontend/react/src/components/layout/Layout.tsx
/**
 * @file Main layout shell component.
 *
 * Composes the {@link Header}, a `<main>` content area (populated by
 * `react-router-dom`'s `<Outlet />`), and the {@link Footer} into a
 * vertical flexbox that fills the viewport.
 */

import React from "react";
import { Outlet } from "react-router-dom";
import { Header } from "./Header";
import { Footer } from "./Footer";

/**
 * Root layout component for the application.
 *
 * Used as the `element` of the top-level `<Route>` so that every
 * page is rendered inside a consistent header / footer shell.
 *
 * @returns The rendered layout wrapping the routed page content.
 *
 * @example
 * ```tsx
 * <Route element={<Layout />}>
 *   <Route path="/" element={<HomePage />} />
 * </Route>
 * ```
 */
export function Layout(): React.JSX.Element {
  return (
    <div className="app-layout">
      <Header />
      <main className="app-main">
        <Outlet />
      </main>
      <Footer />
    </div>
  );
}
