// examples/frontend/vue/src/components/common/ThemeToggle.vue
<!--
  @file Theme toggle button component.

  Renders a button with a sun or moon SVG icon that toggles the
  application between dark and light colour themes using the
  useTheme composable.
-->

<script setup lang="ts">
/**
 * ThemeToggle component.
 *
 * Displays a moon icon when the current theme is dark (clicking
 * switches to light) and a sun icon when the current theme is light
 * (clicking switches to dark).
 */

import { useI18n } from "vue-i18n";
import { useTheme } from "@/composables/useTheme";

const { t } = useI18n();
const { theme, toggleTheme } = useTheme();
</script>

<template>
  <button
    class="btn-icon"
    type="button"
    :title="t('header.toggleTheme')"
    :aria-label="t('header.toggleTheme')"
    @click="toggleTheme"
  >
    <!-- Sun icon -- shown in dark mode; click to go light -->
    <svg
      v-if="theme === 'dark'"
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <circle cx="12" cy="12" r="5" />
      <line x1="12" y1="1" x2="12" y2="3" />
      <line x1="12" y1="21" x2="12" y2="23" />
      <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
      <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
      <line x1="1" y1="12" x2="3" y2="12" />
      <line x1="21" y1="12" x2="23" y2="12" />
      <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
      <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
    </svg>

    <!-- Moon icon -- shown in light mode; click to go dark -->
    <svg
      v-else
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
    </svg>
  </button>
</template>

// examples/frontend/nextjs/src/components/common/ThemeToggle.tsx
/**
 * @file Theme toggle button component.
 *
 * Renders a button with a sun or moon SVG icon that toggles the
 * application between dark and light colour themes using the
 * {@link useTheme} hook.
 */

"use client";

import { useTheme } from "@/hooks/useTheme";
import { useLanguage } from "@/components/common/LanguageSelector";

/**
 * Button that toggles between dark and light themes.
 *
 * Displays a sun icon when the current theme is dark (clicking
 * switches to light) and a moon icon when the current theme is light
 * (clicking switches to dark).
 *
 * @returns The rendered theme toggle button.
 */
export function ThemeToggle(): React.JSX.Element {
  const { theme, toggleTheme } = useTheme();
  const { t } = useLanguage();

  return (
    <button
      className="btn-icon"
      onClick={toggleTheme}
      title={t("header.toggleTheme")}
      aria-label={t("header.toggleTheme")}
      type="button"
    >
      {theme === "dark" ? (
        /* Sun icon -- shown in dark mode; click to go light */
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="5" />
          <line x1="12" y1="1" x2="12" y2="3" />
          <line x1="12" y1="21" x2="12" y2="23" />
          <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
          <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
          <line x1="1" y1="12" x2="3" y2="12" />
          <line x1="21" y1="12" x2="23" y2="12" />
          <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
          <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
        </svg>
      ) : (
        /* Moon icon -- shown in light mode; click to go dark */
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
        </svg>
      )}
    </button>
  );
}
