// examples/frontend/angular/src/app/components/common/loading-spinner.component.ts
/**
 * @file Loading spinner component.
 *
 * Displays a centered CSS spinner animation used as a visual indicator
 * while asynchronous operations (e.g. authentication, data fetching)
 * are in progress.
 */

import { Component } from '@angular/core';

/**
 * Standalone component that renders a loading spinner.
 *
 * @example
 * ```html
 * <app-loading-spinner />
 * ```
 */
@Component({
  selector: 'app-loading-spinner',
  standalone: true,
  templateUrl: './loading-spinner.component.html',
})
export class LoadingSpinnerComponent {}

<!-- Centered loading spinner with accessible label -->
<div class="loading-spinner-container">
  <div class="loading-spinner" role="status" aria-label="Loading">
    <span class="sr-only">Loading...</span>
  </div>
</div>

// examples/frontend/vue/src/components/common/LoadingSpinner.vue
<!--
  @file Reusable loading spinner component.

  Renders a lightweight, CSS-only spinning indicator to communicate
  an in-progress asynchronous operation (e.g. authentication
  initialisation, data fetching).
-->

<script setup lang="ts">
/**
 * LoadingSpinner component.
 *
 * Displays a centred CSS loading spinner. The spinner is implemented
 * as a div with a rotating border. It is wrapped in a full-height
 * container so it centres itself within the available space.
 */
</script>

<template>
  <div class="loading-spinner-container">
    <div class="loading-spinner" aria-label="Loading" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>
</template>
