// examples/frontend/angular/src/app/components/common/theme-toggle.component.ts
/**
 * @file Theme toggle button component.
 *
 * Renders a button that toggles the application between dark and light
 * colour themes.  Displays a sun icon in dark mode and a moon icon in
 * light mode, matching the React example behaviour.
 */

import { Component, inject } from '@angular/core';
import { ThemeService } from '@app/services/theme.service';

/**
 * Standalone component that renders a theme toggle button.
 *
 * @example
 * ```html
 * <app-theme-toggle />
 * ```
 */
@Component({
  selector: 'app-theme-toggle',
  standalone: true,
  templateUrl: './theme-toggle.component.html',
})
export class ThemeToggleComponent {
  /** Theme service injected to read and toggle the current theme. */
  protected readonly themeService = inject(ThemeService);
}

<!-- Theme toggle button: sun for dark mode, moon for light mode -->
<button
  class="theme-toggle"
  type="button"
  [attr.aria-label]="themeService.isDark() ? 'Switch to light theme' : 'Switch to dark theme'"
  [attr.title]="themeService.isDark() ? 'Switch to light theme' : 'Switch to dark theme'"
  (click)="themeService.toggleTheme()"
>
  @if (themeService.isDark()) {
    <!-- Sun icon (shown when dark mode is active) -->
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="12" cy="12" r="5" />
      <line x1="12" y1="1" x2="12" y2="3" />
      <line x1="12" y1="21" x2="12" y2="23" />
      <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
      <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
      <line x1="1" y1="12" x2="3" y2="12" />
      <line x1="21" y1="12" x2="23" y2="12" />
      <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
      <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
    </svg>
  } @else {
    <!-- Moon icon (shown when light mode is active) -->
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
    </svg>
  }
</button>

// examples/frontend/vue/src/components/common/ThemeToggle.vue
<!--
  @file Theme toggle button component.

  Renders a button with a sun or moon SVG icon that toggles the
  application between dark and light colour themes using the
  useTheme composable.
-->

<script setup lang="ts">
/**
 * ThemeToggle component.
 *
 * Displays a moon icon when the current theme is dark (clicking
 * switches to light) and a sun icon when the current theme is light
 * (clicking switches to dark).
 */

import { useI18n } from "vue-i18n";
import { useTheme } from "@/composables/useTheme";

const { t } = useI18n();
const { theme, toggleTheme } = useTheme();
</script>

<template>
  <button
    class="btn-icon"
    type="button"
    :title="t('header.toggleTheme')"
    :aria-label="t('header.toggleTheme')"
    @click="toggleTheme"
  >
    <!-- Sun icon -- shown in dark mode; click to go light -->
    <svg
      v-if="theme === 'dark'"
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <circle cx="12" cy="12" r="5" />
      <line x1="12" y1="1" x2="12" y2="3" />
      <line x1="12" y1="21" x2="12" y2="23" />
      <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
      <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
      <line x1="1" y1="12" x2="3" y2="12" />
      <line x1="21" y1="12" x2="23" y2="12" />
      <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
      <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
    </svg>

    <!-- Moon icon -- shown in light mode; click to go dark -->
    <svg
      v-else
      width="18"
      height="18"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
    </svg>
  </button>
</template>
