// examples/frontend/react/src/pages/NotFoundPage.tsx
/**
 * @file Not Found (404) page.
 *
 * Displayed when the user navigates to a route that does not match
 * any defined path in the application router.
 */

import React from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";

/**
 * Page displayed for unmatched routes (404).
 *
 * Provides a clear "page not found" message and a link to
 * navigate back to the home page.  The visual style is consistent
 * with {@link UnauthorizedPage}.
 *
 * @returns The rendered not-found page.
 *
 * @example
 * ```tsx
 * <Route path="*" element={<NotFoundPage />} />
 * ```
 */
export function NotFoundPage(): React.JSX.Element {
  const { t } = useTranslation();

  return (
    <div className="page page-not-found">
      <h1 className="page-title">{t("notFound.title")}</h1>
      <p className="page-description">{t("notFound.message")}</p>
      <Link to="/" className="btn btn-primary">
        {t("notFound.backHome")}
      </Link>
    </div>
  );
}

// examples/frontend/vue/src/views/NotFoundPage.vue
<!--
  @file Not Found (404) page.

  Displayed when the user navigates to a route that does not match
  any defined application path. Provides a friendly message and a
  link to return to the home page.
-->

<script setup lang="ts">
/**
 * NotFoundPage view component.
 *
 * Renders a "Page Not Found" message with translated content
 * via vue-i18n and offers navigation back to the home page.
 */

import { useI18n } from "vue-i18n";

const { t } = useI18n();
</script>

<template>
  <div class="page page-not-found">
    <h1 class="page-title">{{ t("notFound.title") }}</h1>
    <p class="page-description">{{ t("notFound.message") }}</p>
    <router-link to="/" class="btn btn-primary">
      {{ t("notFound.backHome") }}
    </router-link>
  </div>
</template>
