// examples/frontend/react/src/pages/UnauthorizedPage.tsx
/**
 * @file Unauthorized access page.
 *
 * Shown when an authenticated user attempts to access a resource
 * for which they lack the required role.
 */

import React from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";

/**
 * Page displayed when a user does not have the required role.
 *
 * Provides a clear "permission denied" message and a link to
 * navigate back to the home page.
 *
 * @returns The rendered unauthorized page.
 *
 * @example
 * ```tsx
 * <Route path="/unauthorized" element={<UnauthorizedPage />} />
 * ```
 */
export function UnauthorizedPage(): React.JSX.Element {
  const { t } = useTranslation();

  return (
    <div className="page page-unauthorized">
      <h1 className="page-title">{t("unauthorized.title")}</h1>
      <p className="page-description">{t("unauthorized.message")}</p>
      <Link to="/" className="btn btn-primary">
        {t("unauthorized.backHome")}
      </Link>
    </div>
  );
}

// examples/frontend/vue/src/views/UnauthorizedPage.vue
<!--
  @file Unauthorized access page.

  Shown when an authenticated user attempts to access a resource
  for which they lack the required role.
-->

<script setup lang="ts">
/**
 * UnauthorizedPage view component.
 *
 * Provides a clear "permission denied" message and a link to
 * navigate back to the home page.
 */

import { useI18n } from "vue-i18n";

const { t } = useI18n();
</script>

<template>
  <div class="page page-unauthorized">
    <h1 class="page-title">{{ t("unauthorized.title") }}</h1>
    <p class="page-description">{{ t("unauthorized.message") }}</p>
    <router-link to="/" class="btn btn-primary">
      {{ t("unauthorized.backHome") }}
    </router-link>
  </div>
</template>
