// examples/frontend/angular/src/app/pages/profile/profile.component.ts
/**
 * @file Profile page component.
 *
 * Protected page that displays the full set of OIDC identity token
 * claims as key-value pairs, giving the user visibility into the
 * data stored in their access token.
 */

import { Component, inject } from '@angular/core';
import { AsyncPipe, JsonPipe, KeyValuePipe } from '@angular/common';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { TranslateModule } from '@ngx-translate/core';

/**
 * Standalone profile page component.
 *
 * Iterates over all claims in the user data object and renders them
 * in a vertical list. Complex values (objects/arrays) are displayed
 * as formatted JSON.
 *
 * @example
 * ```html
 * <app-profile />
 * ```
 */
@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [AsyncPipe, JsonPipe, KeyValuePipe, TranslateModule],
  templateUrl: './profile.component.html',
})
export class ProfileComponent {
  /** OIDC service for retrieving user data. */
  protected readonly oidcService = inject(OidcSecurityService);

  /** Observable that emits the user data from the token. */
  readonly userData$ = this.oidcService.userData$;

  /**
   * Determines whether a value is a primitive (string, number, boolean)
   * or a complex object/array that should be rendered as JSON.
   *
   * @param value - The claim value to inspect.
   * @returns `true` if the value is a primitive type.
   */
  isPrimitive(value: unknown): boolean {
    return (
      typeof value === 'string' ||
      typeof value === 'number' ||
      typeof value === 'boolean'
    );
  }

  /**
   * Formats a complex value as a JSON string for display.
   *
   * @param value - The value to format.
   * @returns A pretty-printed JSON string.
   */
  formatValue(value: unknown): string {
    return JSON.stringify(value, null, 2);
  }
}

<!-- Profile page (protected) - shows all OIDC claims -->
<div class="page">
  <h1 class="page-title">{{ 'profile.title' | translate }}</h1>
  <p class="page-description">{{ 'profile.description' | translate }}</p>

  @if (userData$ | async; as userResult) {
    <div class="card">
      <h2 class="card-title">{{ 'profile.claimsTitle' | translate }}</h2>
      <div class="info-list-vertical">
        @for (item of userResult.userData | keyvalue; track item.key) {
          <div class="info-list-item">
            <div class="info-label">{{ item.key }}</div>
            @if (isPrimitive(item.value)) {
              <div class="info-value">{{ item.value }}</div>
            } @else {
              <pre class="claim-json">{{ formatValue(item.value) }}</pre>
            }
          </div>
        }
      </div>
    </div>
  }
</div>

// examples/frontend/nextjs/src/app/profile/page.tsx
/**
 * @file User profile page.
 *
 * Renders a card layout displaying the user's session information
 * and roles from the NextAuth session.
 */

"use client";

import { useSession } from "next-auth/react";
import { useLanguage } from "@/components/common/LanguageSelector";
import { LoadingSpinner } from "@/components/common/LoadingSpinner";

/**
 * Profile page for authenticated users.
 *
 * Displays session information including user name, email, and
 * assigned roles in a definition-list inside a card.
 *
 * @returns The rendered profile page.
 */
export default function ProfilePage(): React.JSX.Element {
  const { data: session, status } = useSession();
  const { t } = useLanguage();

  if (status === "loading") {
    return <LoadingSpinner />;
  }

  const user = session?.user ?? {};
  const roles = session?.roles ?? [];

  /**
   * Formats a claim value for display.
   *
   * @param value - The raw claim value.
   * @returns A human-readable string representation.
   */
  const formatValue = (value: unknown): string => {
    if (value === null || value === undefined) return "-";
    if (typeof value === "object") return JSON.stringify(value, null, 2);
    return String(value);
  };

  // Build profile claims from the session data.
  const claims: Record<string, unknown> = {
    name: user.name,
    email: user.email,
    image: user.image,
    roles: roles,
  };

  return (
    <div className="page page-profile">
      <h1 className="page-title">{t("profile.title")}</h1>
      <p className="page-description">{t("profile.description")}</p>

      <section className="card">
        <h2 className="card-title">{t("profile.claimsTitle")}</h2>
        <dl className="info-list info-list-vertical">
          {Object.entries(claims).map(([key, value]) => (
            <div key={key} className="info-list-item">
              <dt className="info-label">{key}</dt>
              <dd className="info-value">
                {typeof value === "object" ? (
                  <pre className="claim-json">{formatValue(value)}</pre>
                ) : (
                  formatValue(value)
                )}
              </dd>
            </div>
          ))}
        </dl>
      </section>
    </div>
  );
}
