// examples/frontend/vue/src/components/common/LanguageSelector.vue
<!--
  @file Language selector dropdown component.

  Renders a <select> element that allows the user to switch the
  application locale between English (en) and Spanish (es) using
  vue-i18n.
-->

<script setup lang="ts">
/**
 * LanguageSelector component.
 *
 * The component reads the current language from vue-i18n and renders
 * a native <select> with the supported locales. Changing the value
 * updates the locale which triggers a re-render of every component
 * that uses the useI18n composable.
 */

import { useI18n } from "vue-i18n";

const { locale, t } = useI18n();

/**
 * Handles changes to the language select element.
 *
 * @param event - The change event from the select element.
 */
function handleChange(event: Event): void {
  const target = event.target as HTMLSelectElement;
  locale.value = target.value;
}
</script>

<template>
  <select
    class="language-selector"
    :value="locale"
    :aria-label="t('header.selectLanguage')"
    :title="t('header.selectLanguage')"
    @change="handleChange"
  >
    <option value="en">EN</option>
    <option value="es">ES</option>
  </select>
</template>

// examples/frontend/angular/src/app/components/common/language-selector.component.ts
/**
 * @file Language selector component.
 *
 * Renders a native `<select>` element that allows the user to switch
 * between supported application languages (English and Spanish).
 * The selection is applied immediately via the ngx-translate service.
 */

import { Component, inject } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

/**
 * Standalone component that renders a language selector dropdown.
 *
 * @example
 * ```html
 * <app-language-selector />
 * ```
 */
@Component({
  selector: 'app-language-selector',
  standalone: true,
  templateUrl: './language-selector.component.html',
})
export class LanguageSelectorComponent {
  /** The ngx-translate service used to change the active language. */
  protected readonly translate = inject(TranslateService);

  /** List of supported languages. */
  readonly languages = [
    { code: 'en', label: 'EN' },
    { code: 'es', label: 'ES' },
  ];

  /**
   * Handles selection changes from the dropdown.
   *
   * @param event - The native change event from the `<select>` element.
   */
  onLanguageChange(event: Event): void {
    const target = event.target as HTMLSelectElement;
    this.translate.use(target.value);
  }
}

<!-- Language selector dropdown -->
<div class="language-selector">
  <select
    [value]="translate.currentLang || translate.defaultLang"
    (change)="onLanguageChange($event)"
    aria-label="Select language"
  >
    @for (lang of languages; track lang.code) {
      <option [value]="lang.code">{{ lang.label }}</option>
    }
  </select>
</div>
