// examples/frontend/nextjs/src/app/not-found.tsx
/**
 * @file Custom 404 Not Found page for the Next.js App Router.
 *
 * This component is rendered automatically by Next.js when a route does not
 * match any defined page. It displays a localized message with a link back
 * to the home page, using the application's language context.
 *
 * @see {@link https://nextjs.org/docs/app/api-reference/file-conventions/not-found}
 */

"use client";

import Link from "next/link";
import { useLanguage } from "@/components/common/LanguageSelector";

/**
 * Not Found page component.
 *
 * Displays a user-friendly 404 message with localized text and a navigation
 * link back to the home page.
 *
 * @returns The rendered 404 page element.
 */
export default function NotFound(): React.JSX.Element {
  const { t } = useLanguage();

  return (
    <div className="page-container">
      <div className="card" style={{ textAlign: "center" }}>
        <h1
          className="page-title"
          style={{ color: "var(--accent-red)" }}
        >
          {t("notFound.title")}
        </h1>
        <p className="text-muted">{t("notFound.message")}</p>
        <Link
          href="/"
          className="btn btn-primary"
          style={{ marginTop: "16px", display: "inline-block" }}
        >
          {t("notFound.backHome")}
        </Link>
      </div>
    </div>
  );
}

// examples/frontend/angular/src/app/pages/not-found/not-found.component.ts
/**
 * @file Not Found (404) page component.
 *
 * Displayed when a user navigates to a route that does not match any
 * defined application path. Provides a clear "Page Not Found" message
 * and a link back to the home page.
 */

import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';

/**
 * Standalone not-found page component.
 *
 * Renders a user-friendly 404 page with translated content and a
 * navigation link back to the application root. Follows the same
 * layout pattern as {@link UnauthorizedComponent}.
 *
 * @example
 * ```html
 * <app-not-found />
 * ```
 */
@Component({
  selector: 'app-not-found',
  standalone: true,
  imports: [RouterLink, TranslateModule],
  templateUrl: './not-found.component.html',
})
export class NotFoundComponent {}

<!-- Not Found / 404 page -->
<div class="page">
  <h1 class="page-title">{{ 'notFound.title' | translate }}</h1>
  <p class="page-description">{{ 'notFound.message' | translate }}</p>
  <a routerLink="/" class="btn btn-primary">
    {{ 'notFound.backHome' | translate }}
  </a>
</div>
