// examples/frontend/angular/src/app/pages/dashboard/dashboard.component.ts
/**
 * @file Dashboard page component.
 *
 * Protected page that displays the authenticated user's information
 * including their name, email, assigned roles, token expiry countdown,
 * and a truncated access token preview.
 */

import { Component, inject, OnInit, OnDestroy, signal } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { TranslateModule } from '@ngx-translate/core';

/**
 * Standalone dashboard page component.
 *
 * Shows user info, roles, token expiry, and an access token preview.
 * The token expiry countdown is updated every second.
 *
 * @example
 * ```html
 * <app-dashboard />
 * ```
 */
@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [AsyncPipe, TranslateModule],
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent implements OnInit, OnDestroy {
  /** OIDC service for retrieving user data and tokens. */
  protected readonly oidcService = inject(OidcSecurityService);

  /** Observable that emits the user data from the token. */
  readonly userData$ = this.oidcService.userData$;

  /** Signal holding the current access token string. */
  readonly accessToken = signal<string>('');

  /** Signal holding a human-readable token expiry string. */
  readonly tokenExpiry = signal<string>('');

  /** Timer handle for the expiry countdown. */
  private intervalId: ReturnType<typeof setInterval> | null = null;

  /** @inheritDoc */
  ngOnInit(): void {
    this.oidcService.getAccessToken().subscribe((token) => {
      this.accessToken.set(token ?? '');
      this.updateTokenExpiry(token);
    });

    this.intervalId = setInterval(() => {
      const token = this.accessToken();
      if (token) {
        this.updateTokenExpiry(token);
      }
    }, 1000);
  }

  /** @inheritDoc */
  ngOnDestroy(): void {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
    }
  }

  /**
   * Extracts the display name from the user data.
   *
   * @param userData - The decoded token user data.
   * @returns The user's display name.
   */
  getUserName(userData: Record<string, unknown> | null): string {
    if (!userData) return '';
    return (
      (userData['preferred_username'] as string) ??
      (userData['name'] as string) ??
      ''
    );
  }

  /**
   * Extracts the user's email from the user data.
   *
   * @param userData - The decoded token user data.
   * @returns The user's email or null.
   */
  getEmail(userData: Record<string, unknown> | null): string | null {
    if (!userData) return null;
    return (userData['email'] as string) ?? null;
  }

  /**
   * Extracts the realm roles from the user data.
   *
   * @param userData - The decoded token user data.
   * @returns An array of role name strings.
   */
  getRoles(userData: Record<string, unknown> | null): string[] {
    if (!userData) return [];
    const realmAccess = userData['realm_access'] as
      | { roles?: string[] }
      | undefined;
    return realmAccess?.roles ?? [];
  }

  /**
   * Returns a truncated preview of the access token.
   *
   * @param token - The full access token string.
   * @param maxLen - Maximum characters to display.
   * @returns The truncated token string.
   */
  getTokenPreview(token: string, maxLen = 80): string {
    if (!token) return '';
    return token.length > maxLen ? token.substring(0, maxLen) + '...' : token;
  }

  /**
   * Returns the CSS class for a role badge.
   *
   * @param role - The role name.
   * @returns The CSS class string.
   */
  getRoleBadgeClass(role: string): string {
    if (role === 'admin') return 'badge badge-admin';
    if (role === 'user') return 'badge badge-user';
    return 'badge';
  }

  /**
   * Decodes the JWT access token and updates the expiry countdown
   * signal.
   *
   * @param token - The raw JWT access token string.
   */
  private updateTokenExpiry(token: string): void {
    try {
      const payload = JSON.parse(atob(token.split('.')[1]));
      const exp = payload.exp as number;
      const now = Math.floor(Date.now() / 1000);
      const diff = exp - now;

      if (diff <= 0) {
        this.tokenExpiry.set('expired');
      } else {
        const minutes = Math.floor(diff / 60);
        const seconds = diff % 60;
        this.tokenExpiry.set(
          `${minutes}m ${seconds.toString().padStart(2, '0')}s`,
        );
      }
    } catch {
      this.tokenExpiry.set('');
    }
  }
}

<!-- Dashboard page (protected) -->
<div class="page">
  @if (userData$ | async; as userResult) {
    <h1 class="page-title">
      {{ 'dashboard.welcome' | translate:{ name: getUserName(userResult.userData) } }}
    </h1>

    <!-- User Information Card -->
    <div class="card" style="margin-bottom: var(--spacing-lg)">
      <h2 class="card-title">{{ 'dashboard.userInfo' | translate }}</h2>
      <dl class="info-list">
        <dt>{{ 'dashboard.name' | translate }}</dt>
        <dd>{{ getUserName(userResult.userData) || ('dashboard.notProvided' | translate) }}</dd>

        <dt>{{ 'dashboard.email' | translate }}</dt>
        <dd>{{ getEmail(userResult.userData) || ('dashboard.notProvided' | translate) }}</dd>
      </dl>
    </div>

    <!-- Roles Card -->
    <div class="card" style="margin-bottom: var(--spacing-lg)">
      <h2 class="card-title">{{ 'dashboard.roles' | translate }}</h2>
      @if (getRoles(userResult.userData).length > 0) {
        <div class="badge-group">
          @for (role of getRoles(userResult.userData); track role) {
            <span [class]="getRoleBadgeClass(role)">{{ role }}</span>
          }
        </div>
      } @else {
        <p class="text-muted">{{ 'dashboard.noRoles' | translate }}</p>
      }
    </div>

    <!-- Token Info Card -->
    <div class="card" style="margin-bottom: var(--spacing-lg)">
      <h2 class="card-title">{{ 'dashboard.tokenInfo' | translate }}</h2>
      <dl class="info-list">
        <dt>{{ 'dashboard.tokenExpiry' | translate }}</dt>
        <dd>
          @if (tokenExpiry() === 'expired') {
            <span class="text-muted">{{ 'dashboard.expired' | translate }}</span>
          } @else {
            <span class="token-countdown">{{ tokenExpiry() }}</span>
          }
        </dd>
      </dl>
    </div>

    <!-- Access Token Preview Card -->
    <div class="card">
      <h2 class="card-title">{{ 'dashboard.accessToken' | translate }}</h2>
      <code class="token-preview">{{ getTokenPreview(accessToken()) }}</code>
    </div>
  }
</div>

// examples/frontend/nextjs/src/app/dashboard/page.tsx
/**
 * @file Protected dashboard page.
 *
 * Shows key information about the authenticated user: display name,
 * email, assigned roles (rendered as badges), token expiry countdown,
 * and a truncated preview of the access token.
 */

"use client";

import { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { useLanguage } from "@/components/common/LanguageSelector";
import { LoadingSpinner } from "@/components/common/LoadingSpinner";

/**
 * Formats a number of seconds into a human-readable `MM:SS` string.
 *
 * @param seconds - Total remaining seconds (may be negative).
 * @returns A string in `"MM:SS"` format, or `"00:00"` when the value
 *          is zero or negative.
 */
function formatCountdown(seconds: number): string {
  if (seconds <= 0) return "00:00";
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
}

/**
 * Dashboard page for authenticated users.
 *
 * Displays user info, roles, token expiry countdown, and access
 * token preview.
 *
 * @returns The rendered dashboard page.
 */
export default function DashboardPage(): React.JSX.Element {
  const { data: session, status } = useSession();
  const { t } = useLanguage();
  const [secondsLeft, setSecondsLeft] = useState<number>(0);

  const name = session?.user?.name ?? "";
  const email = session?.user?.email ?? "";
  const roles = session?.roles ?? [];

  /* ---------- Token expiry countdown ---------- */
  useEffect(() => {
    // NextAuth sessions do not directly expose expires_at, but we can
    // estimate from the session expiry.
    const update = (): void => {
      if (session?.expires) {
        const expiresAt = new Date(session.expires).getTime() / 1000;
        setSecondsLeft(Math.floor(expiresAt - Date.now() / 1000));
      }
    };
    update();
    const id = setInterval(update, 1000);
    return () => clearInterval(id);
  }, [session?.expires]);

  /* ---------- Access token preview ---------- */
  const accessToken = session?.accessToken ?? "";
  const tokenPreview = accessToken.length > 40
    ? `${accessToken.slice(0, 20)}...${accessToken.slice(-20)}`
    : accessToken;

  if (status === "loading") {
    return <LoadingSpinner />;
  }

  return (
    <div className="page page-dashboard">
      <h1 className="page-title">{t("dashboard.title")}</h1>

      {/* User info card */}
      <section className="card">
        <h2 className="card-title">{t("dashboard.userInfo")}</h2>
        <dl className="info-list">
          <dt>{t("dashboard.name")}</dt>
          <dd>{name}</dd>
          <dt>{t("dashboard.email")}</dt>
          <dd>{email || <span className="text-muted">{t("dashboard.notProvided")}</span>}</dd>
        </dl>
      </section>

      {/* Roles card */}
      <section className="card">
        <h2 className="card-title">{t("dashboard.roles")}</h2>
        <div className="badge-group">
          {roles.map((role) => (
            <span key={`realm-${role}`} className="badge badge-realm" title={t("dashboard.realmRole")}>
              {role}
            </span>
          ))}
          {roles.length === 0 && (
            <span className="text-muted">{t("dashboard.noRoles")}</span>
          )}
        </div>
      </section>

      {/* Token expiry card */}
      <section className="card">
        <h2 className="card-title">{t("dashboard.tokenExpiry")}</h2>
        <p className="token-countdown">
          {secondsLeft > 0
            ? t("dashboard.expiresIn", { time: formatCountdown(secondsLeft) })
            : t("dashboard.expired")}
        </p>
      </section>

      {/* Access token preview card */}
      <section className="card">
        <h2 className="card-title">{t("dashboard.accessToken")}</h2>
        <code className="token-preview">{tokenPreview || <span className="text-muted">-</span>}</code>
      </section>
    </div>
  );
}
