// examples/frontend/nextjs/src/app/admin/page.tsx
/**
 * @file Admin-only page.
 *
 * Displays content restricted to users who hold the `admin` role.
 * Access is enforced at the middleware level; this component assumes
 * the user has already been authorised.
 */

"use client";

import { useSession } from "next-auth/react";
import { useLanguage } from "@/components/common/LanguageSelector";
import { LoadingSpinner } from "@/components/common/LoadingSpinner";

/**
 * Administration page.
 *
 * Shown only to authenticated users who possess the `admin` role.
 * Displays a welcome message and a placeholder section for
 * admin-specific actions.
 *
 * @returns The rendered admin page.
 */
export default function AdminPage(): React.JSX.Element {
  const { data: session, status } = useSession();
  const { t } = useLanguage();

  if (status === "loading") {
    return <LoadingSpinner />;
  }

  const userName = session?.user?.name ?? "";

  return (
    <div className="page page-admin">
      <h1 className="page-title">{t("admin.title")}</h1>
      <p className="page-description">
        {t("admin.welcome", { name: userName })}
      </p>

      <section className="card">
        <h2 className="card-title">{t("admin.panelTitle")}</h2>
        <p>{t("admin.panelDescription")}</p>
        <ul className="admin-actions">
          <li>{t("admin.actionUsers")}</li>
          <li>{t("admin.actionRoles")}</li>
          <li>{t("admin.actionSettings")}</li>
        </ul>
      </section>
    </div>
  );
}

// examples/frontend/angular/src/app/pages/admin/admin.component.ts
/**
 * @file Admin page component.
 *
 * Protected page that requires the `admin` realm role. Displays
 * administrative content and a list of available admin actions.
 */

import { Component, inject } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { OidcSecurityService } from 'angular-auth-oidc-client';
import { TranslateModule } from '@ngx-translate/core';

/**
 * Standalone admin page component.
 *
 * Only accessible to users with the `admin` role (enforced by the
 * route guard). Displays an admin panel with available actions.
 *
 * @example
 * ```html
 * <app-admin />
 * ```
 */
@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [AsyncPipe, TranslateModule],
  templateUrl: './admin.component.html',
})
export class AdminComponent {
  /** OIDC service for retrieving user data. */
  protected readonly oidcService = inject(OidcSecurityService);

  /** Observable that emits the user data from the token. */
  readonly userData$ = this.oidcService.userData$;

  /**
   * Extracts the display name from the user data.
   *
   * @param userData - The decoded token user data.
   * @returns The user's display name.
   */
  getUserName(userData: Record<string, unknown> | null): string {
    if (!userData) return '';
    return (
      (userData['preferred_username'] as string) ??
      (userData['name'] as string) ??
      ''
    );
  }
}

<!-- Admin page (requires admin role) -->
<div class="page">
  <h1 class="page-title">{{ 'admin.title' | translate }}</h1>

  @if (userData$ | async; as userResult) {
    <p class="page-description">
      {{ 'admin.welcome' | translate:{ name: getUserName(userResult.userData) } }}
    </p>
  }

  <div class="card">
    <h2 class="card-title">{{ 'admin.panelTitle' | translate }}</h2>
    <p class="page-description">{{ 'admin.panelDescription' | translate }}</p>
    <ul class="admin-actions">
      <li>{{ 'admin.actionUsers' | translate }}</li>
      <li>{{ 'admin.actionRoles' | translate }}</li>
      <li>{{ 'admin.actionSettings' | translate }}</li>
    </ul>
  </div>
</div>
