// examples/frontend/angular/src/app/pages/unauthorized/unauthorized.component.ts
/**
 * @file Unauthorized page component.
 *
 * Displayed when a user attempts to access a route they do not have
 * permission for (e.g. missing the required role). Provides a clear
 * "Access Denied" message and a link back to the home page.
 */

import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';

/**
 * Standalone unauthorized page component.
 *
 * @example
 * ```html
 * <app-unauthorized />
 * ```
 */
@Component({
  selector: 'app-unauthorized',
  standalone: true,
  imports: [RouterLink, TranslateModule],
  templateUrl: './unauthorized.component.html',
})
export class UnauthorizedComponent {}

<!-- Unauthorized / Access Denied page -->
<div class="page">
  <h1 class="page-title">{{ 'unauthorized.title' | translate }}</h1>
  <p class="page-description">{{ 'unauthorized.message' | translate }}</p>
  <a routerLink="/" class="btn btn-primary">
    {{ 'unauthorized.backHome' | translate }}
  </a>
</div>

// examples/frontend/nextjs/src/app/unauthorized/page.tsx
/**
 * @file Unauthorized access page.
 *
 * Shown when an authenticated user attempts to access a resource
 * for which they lack the required role.
 */

"use client";

import Link from "next/link";
import { useLanguage } from "@/components/common/LanguageSelector";

/**
 * Page displayed when a user does not have the required role.
 *
 * Provides a clear "permission denied" message and a link to
 * navigate back to the home page.
 *
 * @returns The rendered unauthorized page.
 */
export default function UnauthorizedPage(): React.JSX.Element {
  const { t } = useLanguage();

  return (
    <div className="page page-unauthorized">
      <h1 className="page-title">{t("unauthorized.title")}</h1>
      <p className="page-description">{t("unauthorized.message")}</p>
      <Link href="/" className="btn btn-primary">
        {t("unauthorized.backHome")}
      </Link>
    </div>
  );
}
